### PR TITLE
F#39 better tracking

### PR DESCRIPTION
**Pull request by ghost**
Probability map calculation improved with a motion detection.

### CODE REVIEW

**Comment by VahidAminZ** [comment]
new changes seem fine but why so many lint errors?

**Comment by ghost** [comment]
These errors come from another package (point_cloud) and their fix are the point of another PR. I'm trying to fix them right now.

**Comment by VahidAminZ** [comment]
In that case unless you urgently want this to be merged maybe we can wait for those modifications and merge a clean build?

**Comment by ghost** [comment]
Yes we can.

**Comment by ugocupcic** [comment]
@mewine closing that one - you need to open it against indigo-devel

**Pull request closed without merging**
