### PR TITLE
F#37 roslint fixes

### PR DESCRIPTION
**Pull request by ghost**
Fixed the build issues

### CODE REVIEW

**Comment by ghost** [comment]
I fixed all the linter errors I could, don't want to break something with the other ones. 
I also ran the tests manually and they all pass. Don't now why Shippable can't run the one for cluster_segmentor...

**Comment by AndriyPt** [comment]
@mewine this is the main idea of the PR and branches in git. You have your own sandbox where you can play and do not interfere with other people. Once you have finished you will have other person to review all your work and after that it will be merged to indigo-devel. My suggestion for you is to proceed with roslint errors fixes. I will have a look on the cluster_segmentor errors. Lets make build green :)

**Comment by ghost** [comment]
I fixed all errors in sr_vision Python files, and a number in the cpp files. I can't manage to fix the remaining ones (non const reference for the most of them) properly, because of their original definition. Could you have a look on them ?

**Comment by ugocupcic** [comment]
@mewine @AndriyPt what's up with that one? Would be great to have this fixed soon ;)

**Comment by AndriyPt** [comment]
we'll do our best to fix it soon :)

**Comment by ghost** [comment]
Yes :)
I'm fixing the new errors introduced with sr_extrinsic_calibration.

**Pull request merged**
